[from-provider]
exten => _X.,1,Goto(ascn-inbound-handler,s,1)
exten => _+X.,1,Goto(ascn-inbound-handler,s,1)
exten => s,1,Goto(ascn-inbound-handler,s,1)

[ascn-inbound-handler]
exten => s,1,NoOp(ASCN incoming voice call from ${CALLERID(num)})
 same => n,Set(ASCN_CALL_UUID=)
 same => n,AGI(agi://voice-gateway:4573/register?tenantId=${ASCN_TENANT_ID}&connectionId=${ASCN_CONNECTION_ID})
 same => n,GotoIf($["${ASCN_CALL_UUID}" = ""]?capacity-full)
 same => n,Answer()
 same => n,AudioSocket(${ASCN_CALL_UUID},voice-gateway:9092)
 same => n,Hangup()
 same => n(capacity-full),Busy(10)
 same => n,Hangup()

[ascn-outbound]
exten => s,1,NoOp(ASCN outbound voice call ${ASCN_CALL_UUID})
 same => n,Set(ASCN_REQUESTED_CALL_UUID=${ASCN_CALL_UUID})
 same => n,Set(ASCN_CALL_UUID=)
 same => n,AGI(agi://voice-gateway:4573/register?uuid=${ASCN_REQUESTED_CALL_UUID})
 same => n,GotoIf($["${ASCN_CALL_UUID}" = ""]?capacity-rejected)
 same => n,Answer()
 same => n,AudioSocket(${ASCN_CALL_UUID},voice-gateway:9092)
 same => n,Hangup()
 same => n(capacity-rejected),Hangup(34)

[ascn-transfer]
exten => _X.,1,Dial(PJSIP/${EXTEN}@${ASCN_ENDPOINT},45)
 same => n,Hangup()
