[from-provider]
exten => _X.,1,NoOp(ASCN incoming voice call from ${CALLERID(num)})
 same => n,Answer()
 same => n,AGI(agi://voice-gateway:4573/register)
 same => n,AudioSocket(${ASCN_CALL_UUID},voice-gateway:9092)
 same => n,Hangup()

[ascn-outbound]
exten => s,1,NoOp(ASCN outbound voice call ${ASCN_CALL_UUID})
 same => n,Answer()
 same => n,AGI(agi://voice-gateway:4573/register?uuid=${ASCN_CALL_UUID})
 same => n,AudioSocket(${ASCN_CALL_UUID},voice-gateway:9092)
 same => n,Hangup()

[ascn-transfer]
exten => _X.,1,Dial(PJSIP/${EXTEN}@${ASCN_ENDPOINT},45)
 same => n,Hangup()
